"""Add pending

Revision ID: 0285ad23e03f
Revises: c6c8966319fc
Create Date: 2024-11-30 14:19:35.753498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0285ad23e03f'
down_revision: Union[str, None] = 'c6c8966319fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_referral_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('tickets', sa.Integer(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_referral_rewards_id'), 'pending_referral_rewards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_referral_rewards_id'), table_name='pending_referral_rewards')
    op.drop_table('pending_referral_rewards')
    # ### end Alembic commands ###
