"""Add new tables

Revision ID: 44b6df63a3d6
Revises: 0c769a636fb1
Create Date: 2024-11-08 16:18:14.776530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b6df63a3d6'
down_revision: Union[str, None] = '0c769a636fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tokens', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tickets', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('other_tg_data', sa.JSON(), nullable=True))
    op.drop_index('ix_users_tgID', table_name='users')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['parent_id'], ['id'])
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'tgID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tgID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_index('ix_users_tgID', 'users', ['tgID'], unique=True)
    op.drop_column('users', 'other_tg_data')
    op.drop_column('users', 'parent_id')
    op.drop_column('users', 'language')
    op.drop_column('users', 'last_login_date')
    op.drop_column('users', 'registration_date')
    op.drop_column('users', 'tickets')
    op.drop_column('users', 'tokens')
    op.drop_column('users', 'coins')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
