"""Add pending referral rewards

Revision ID: 5b435d1b4bd1
Revises: fbf4f8ccd1d3
Create Date: 2024-11-30 14:11:28.064212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b435d1b4bd1'
down_revision: Union[str, None] = 'fbf4f8ccd1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
