"""Rename Task Type

Revision ID: fbf4f8ccd1d3
Revises: 453455cfd159
Create Date: 2024-11-14 21:25:21.535398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf4f8ccd1d3'
down_revision: Union[str, None] = '453455cfd159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('tasks', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'type')
    # ### end Alembic commands ###
